//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public int KategoriID { get; set; }
        public string Kname { get; set; }
        public string KAciklama { get; set; }
        public string KResmi { get; set; }
    }
}
