//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StajProjeEntities4 : DbContext
    {
        public StajProjeEntities4()
            : base("name=StajProjeEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<Urunler> Urunler { get; set; }
        public DbSet<Yonetici> Yonetici { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Sepet> Sepet { get; set; }
    }
}
