//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace denemee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int UrunID { get; set; }
        public string UrunName { get; set; }
        public int UrunFiyat { get; set; }
        public string UrunResmi { get; set; }
        public string UrunAciklama { get; set; }
        public int UrunYoneticiID { get; set; }
        public int UrunKategoriID { get; set; }
    }
}
